<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/fa/tl_settings.php 
 * 
 * Contao extension: BackupDB 3.2.2 
 * Persian translation file 
 * 
 * Copyright : 2007-2015 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Softleister (do_while), http://www.softleister.de 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['0'] = "تعداد پشتیبان‌ها در AutoBackupDB";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_legend'] = "تنظیمات BackupDB";
 
?>
