<?php
/**
 * TL_ROOT/system/modules/BackupDB/languages/ru/tl_settings.php 
 * 
 * Contao extension: BackupDB 3.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : 2007-2014 by Softleister 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Softleister (do_while), http://www.softleister.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['0'] = "Таблицы данных шаблона веб-сайта";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_saveddb']['1'] = "Разделенный запятыми список таблиц для включения в шаблон веб-сайта. Все таблицы ядра Contao  начинаются с префикса <em>tl_</em>, таблицы каталога могут иметь префикс <em>cat_</em>.";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['0'] = "Количество резервных копий AutoBackupDB";
$GLOBALS['TL_LANG']['tl_settings']['AutoBackupCount']['1'] = "Количество файлов резервных копий, созданных AutoBackupDB, значение по умолчанию — 3. Самая последняя копия всегда находится в файле <em>AutoBackupDB-1.sql</em>.";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['0'] = "Альтернативный путь для шаблонов сайта";
$GLOBALS['TL_LANG']['tl_settings']['WsTemplatePath']['1'] = "Путь по умолчанию - <em>templates</em>. Вы можете указать другую папку, в которой хранятся шаблоны веб-сайта.";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_blacklist']['0'] = "Список исключений резервной копии";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_blacklist']['1'] = "Разделенный запятыми список таблиц, которые будут исключены из резервной копии. Например, таблицы <em>tl_lock, tl_log, tl_search, tl_search_index, tl_session, tl_undo, tl_version</em> не нужны для восстановления.";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_sendmail']['0'] = "Уведомлять по электронной почте после AutoBackup";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_sendmail']['1'] = "Отправляет письмо администратору после успешного резервного копирования.";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_attmail']['0'] = "Прикрепить файл резервной копии";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_attmail']['1'] = "Прикрепить файл резервной копии к уведомлению по электронной почте.";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_zip']['0'] = "Сжимать резервные копии";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_zip']['1'] = "Резервная копия может быть сжата в ZIP-архив.";
$GLOBALS['TL_LANG']['tl_settings']['backupdb_legend'] = "Настройки BackupDB";
 
?>
